# Generated by Django 4.1.1 on 2022-10-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(blank=True, max_length=250)),
                ('refreshToken', models.CharField(blank=True, max_length=250)),
                ('expires', models.IntegerField()),
            ],
        ),
    ]
