# Generated by Django 4.1.1 on 2022-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_canvastoken_created_canvastoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvastoken',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
