swagger: '2.0'
info:
  title: Attendance Face Recognition API
  description: Attendance biometric web application
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: tun77242@temple.edu
  license:
    name: BSD License
  version: v1.0.2
host: localhost:5000
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
paths:
  /v1/:
    get:
      operationId: v1_list
      description: Return general info about the user
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/attendance/:
    get:
      operationId: v1_attendance_list
      description: Student taking attendance
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    post:
      operationId: v1_attendance_create
      description: Student taking attendance
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/attendance/monitoring/:
    get:
      operationId: v1_attendance_monitoring_list
      description: View Attendance of a section
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/attendance/monitoring{format}:
    get:
      operationId: v1_attendance_read
      description: View Attendance of a section
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/attendance{format}:
    get:
      operationId: v1_read
      description: Student taking attendance
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    post:
      operationId: v1_create
      description: Student taking attendance
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/courses/:
    get:
      operationId: v1_courses_list
      description: Teacher course attendance configuration
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    post:
      operationId: v1_courses_create
      description: Teacher course attendance configuration
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/courses{format}:
    get:
      operationId: v1_read
      description: Teacher course attendance configuration
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    post:
      operationId: v1_create
      description: Teacher course attendance configuration
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/registration/:
    get:
      operationId: v1_registration_list
      description: Upload and Encode student images
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    post:
      operationId: v1_registration_create
      description: Upload and Encode student images
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/registration{format}:
    get:
      operationId: v1_read
      description: Upload and Encode student images
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    post:
      operationId: v1_create
      description: Upload and Encode student images
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/report/today/:
    get:
      operationId: v1_report_today_list
      description: View attendance report
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/report/today{format}:
    get:
      operationId: v1_report_read
      description: View attendance report
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/statistics/attendance/:
    get:
      operationId: v1_statistics_attendance_list
      description: return total number of late, present, and absent
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/statistics/attendance{format}:
    get:
      operationId: v1_statistics_read
      description: return total number of late, present, and absent
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/statistics/sections/:
    get:
      operationId: v1_statistics_sections_list
      description: return total number of students per section
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/statistics/sections{format}:
    get:
      operationId: v1_statistics_read
      description: return total number of students per section
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/token/:
    post:
      operationId: v1_token_create
      description: Generate user token based of the info received from canvas
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters: []
  /v1/token{format}:
    post:
      operationId: v1_create
      description: Generate user token based of the info received from canvas
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
  /v1/{format}:
    get:
      operationId: v1_read
      description: Return general info about the user
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - v1
    parameters:
      - name: format
        in: path
        required: true
        type: string
definitions: {}
