openapi: 3.0.2
info:
  title: AFR API
  version: 0.1.0
paths:
  /token:
    post:
      summary: Generate Token
      description: |-
        generate access token
        :param data:
        :return: token
      operationId: generate_token_token_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userData'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /attendance:
    post:
      summary: Take Attendance
      description: |-
        user picture to be verified by the application
        :param file:
        :return:
      operationId: take_attendance_attendance_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_take_attendance_attendance_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /report:
    get:
      summary: Attendance Report
      description: |-
        A detail report of user's attendance
        :return:
      operationId: attendance_report_report_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /register:
    post:
      summary: Register User
      description: |-
        Upload multiple profile picture to help the system recognize a user
        :param file:
        :return:
      operationId: register_user_register_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_register_user_register_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_register_user_register_post:
      title: Body_register_user_register_post
      required:
        - file
      type: object
      properties:
        file:
          title: File
          type: string
          format: binary
    Body_take_attendance_attendance_post:
      title: Body_take_attendance_attendance_post
      required:
        - file
      type: object
      properties:
        file:
          title: File
          type: string
          format: binary
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    userData:
      title: userData
      required:
        - sortable_name
        - email
        - canvasId
      type: object
      properties:
        sortable_name:
          title: Sortable Name
          type: string
        email:
          title: Email
          type: string
        canvasId:
          title: Canvasid
          type: integer
