# Generated by Django 4.1.1 on 2022-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvasId', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=50)),
                ('course_number', models.CharField(max_length=10)),
            ],
        ),
    ]
