# Generated by Django 4.1.1 on 2022-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_remove_student_user_delete_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sisId',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
